# Generated by Django 4.2.27 on 2025-12-17 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('mount', 'Mount Point'), ('internal', 'Internal')], max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_type', models.CharField(choices=[('energy', 'Energy'), ('compute', 'Compute'), ('mechanical', 'Mechanical')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Spaceship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaceships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=50)),
                ('stats', models.JSONField(default=dict)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='api.node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='spaceship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.spaceship'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField()),
                ('params', models.JSONField(default=dict)),
                ('demands', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('spaceship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.spaceship')),
            ],
        ),
        migrations.CreateModel(
            name='Conduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField()),
                ('efficiency', models.FloatField(default=1.0)),
                ('level', models.IntegerField(default=1)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='api.node')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resourcetype')),
                ('spaceship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduits', to='api.spaceship')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='api.node')),
            ],
        ),
    ]
