# Generated by Django 4.2.27 on 2025-12-17 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_type', models.CharField(choices=[('energy', 'Energy'), ('compute', 'Compute'), ('mechanical', 'Mechanical')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='stats',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField()),
                ('params', models.JSONField(default=dict)),
                ('demands', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('spaceship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.spaceship')),
            ],
        ),
        migrations.CreateModel(
            name='Conduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField()),
                ('efficiency', models.FloatField(default=1.0)),
                ('level', models.IntegerField(default=1)),
                ('from_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='api.part')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resourcetype')),
                ('spaceship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduits', to='api.spaceship')),
                ('to_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='api.part')),
            ],
        ),
    ]
